### PR TITLE
Fix deps frontend

### PR DESCRIPTION
**Pull request by ezackr**
Merge branch "fix-deps-frontend"
Should replace the old version of App.js, add screens, update necessary dependencies, etc.

### CODE REVIEW

**Comment by ezackr** [comment]
should override App.js and LoginScreen.js

**Review by jpete4 — APPROVED** [review]
Looks good to me

**Comment by jpete4** [comment]
The merge conflict should be fixed, but I believe the tests are still failing - I'd like to see that figured out, but I don't have the node skills to do so.

**Comment by jpete4** [comment]
i lied about the skills - Elliot please review my changes?

**Comment by ezackr** [comment]
lgtm! Nice job with the dependencies, I couldn't seem to figure that part out. Thank you!

**Pull request merged**
